### ISSUE TITLE
gulp-svg-sprites generates blank svg sprite

### ISSUE THREAD

**Issue by meecrobe** [shakyShane/gulp-svg-sprites#104]
No errors but the sprite looks like this:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0" viewBox="0 0 0 0"></svg>`

**Comment by grippado** [comment]
duplicate with https://github.com/shakyShane/gulp-svg-sprites/issues/61
