### ISSUE TITLE
Minimal font-size in Chrome is 12px by default

### ISSUE THREAD

**Issue by corangar** [shakyShane/gulp-svg-sprites#39]
Not sure how this is supposed to work with font-size scaling. Chrome for example has minimal 12px font-size by default so the rendered icons look cropped (right and bottom edges are cut off): https://dl.dropboxusercontent.com/spa/1dqminp255vakv6/cgu20ie6.png

When I go to (Chrome) settings and set the minimal font-size to 10px it works as intended, but I leave it on 12px default purposely always, including when developing since this will be the default behaviour for most users.

I saw your plan to add the option to change the base font-size, but I'm not sure if this really is the way to go. Different clients / devices / user's preference (visually impaired) can influence this issue regardless of our "safe size asumptions" and then the sprite breaks again without any way for us to know or affect this.

**Comment by soenkekluth** [comment]
just set the baseSize option and if needed load your own css template.
