### ISSUE TITLE
Consider providing a JS loading script

### ISSUE THREAD

**Issue by davidtheclark** [shakyShane/gulp-svg-sprites#52]
What would you think about providing a JS loading script when the sprite is generated?

I'm using the `<symbol>` pattern, and instead of pasting the contents of the SVG file into the head of my doc I'd like to keep the spritesheet external and then inline the contents via AJAX (so the sprite is both cached separately from the page and loaded asynchronously).

(Grunticon, for example, generates a simple loading script and provides it along with the other generated resources. Or here's an example somebody wrote for grunt-svgstore: https://gist.github.com/w0rm/621a56a353f7b2a6b0db.)

**Comment by soenkekluth** [comment]
we only provide the core generation of the svg sprite - this should not be part of it
