### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by WaheedJ** [shakyShane/gulp-svg-sprites#62]
When I write, npm install gulp-svg-sprites, I'm being told in the cmd,

npm ERR! 404 'gulp-svg-sprites' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by soenkekluth** [comment]
has to be a local configuration problem.
