### ISSUE TITLE
Install fails on v0.11.14

### ISSUE THREAD

**Issue by chodorowicz** [shakyShane/gulp-svg-sprites#64]
It starts with warning

```npm WARN engine svg-cleaner@0.0.3: wanted: {"node":"0.6.x"} (current: {"node":"0.11.14","npm":"2.1.3"})```

and then lot of errors appear
```
In file included from ../src/libxmljs.cc:8:
../src/xml_document.h:11:34: error: expected class name
class XmlDocument : public node::ObjectWrap {
```

**Comment by petermac-** [comment]
+1, I was able to get libxmljs installed on Windows 8.1 x64 after some troubleshooting but then I ran into errors with phantom-sync...anyone else having the same issue?

**Comment by anatomic** [comment]
@shakyShane has there been any movement on this issue as we're still seeing the problem with libxmljs on node 0.12.1?

**Comment by soenkekluth** [comment]
the current version 4.0.0 does not depend on libxml anymore. please update.
