### ISSUE TITLE
Do not export .no-svg if no fallback used

### ISSUE THREAD

**Issue by silentroach** [shakyShane/gulp-svg-sprites#76]
I use webpack so every time a get an error on this block:

    .no-svg .icon:before {
        background-image: url("../svg/sprite.png");
    }

I don't need a png fallback, so it will be great to disable it.

**Comment by danielfeelfine** [comment]
+1

**Comment by shakyShane** [comment]
@silentroach could you provide a sample webpack config where you're using this please :)
