### ISSUE TITLE
Random character added before classes

### ISSUE THREAD

**Issue by aderaaij** [shakyShane/gulp-svg-sprites#78]
Hi, thanks for this amazing plugin. I've been using it in symbol mode and all is well, except for the fact that the plugin seems to add a random character to classes I defined in my loose svg files. For example, the class `icon--play` becomes `hicon--play`. Is there any simple way to prevent this from happening? It makes it kind of difficult to target my classes ;).

**Comment by soenkekluth** [comment]
should work if you set the common attribute in your config. by default its icon. the problem should not occur in the current version.
