### ISSUE TITLE
node 4.1.1

### ISSUE THREAD

**Issue by batmandarkside** [shakyShane/gulp-svg-sprites#79]
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V86IsDeadEv
  Referenced from: node_modules/gulp-svg-sprites/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v82V86IsDeadEv
  Referenced from: node_modules/gulp-svg-sprites/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: dynamic lookup

**Comment by soenkekluth** [comment]
version 4.0.0 does not depend on libxml anymore. problem should be solved though.
