### ISSUE TITLE
still accept PR's? or add Maintainer

### ISSUE THREAD

**Issue by soenkekluth** [shakyShane/gulp-svg-sprites#80]
PR'd on your svg-sprite-data project on the weekend already.
do you still accept PR's here or would you add me to the repo and npm so i can push this a little further. I already switched from dust to lodash templating in https://github.com/soenkekluth/gulp-svg-sprites
and away from libxmljs in https://github.com/soenkekluth/svg-sprite-data which led to a lot aof problems on several os configurations... 
I really would love to see the npm module getting updated. 
your recommended alternative "gulp-svg-sprite" is a waste

**Comment by shakyShane** [comment]
Happy to let you continue with the this module - just make sure you begin your changes on a major semver version. I will add you to the correct repos/npm tomorrow

**Comment by soenkekluth** [comment]
hey @shakyShane would you mind adding me ? :) still see the most potential in your lib with that few changes. with more to come..

**Comment by shakyShane** [comment]
@soenkekluth sure

**Comment by shakyShane** [comment]
Invite sent

**Comment by soenkekluth** [comment]
@shakyShane perfect thanks!

**Comment by shakyShane** [comment]
You are welcome!

do as you see fit, no need to verify anything with me. When it's at a point you'd like it released to NPM, just give me a shout :)
