### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by soenkekluth** [shakyShane/gulp-svg-sprites#84]
@shakyShane would you please :)

**Comment by soenkekluth** [comment]
@shakyShane would you mind adding me to npm so i can publish on my own by simply typing:
`npm owner add soenkekluth`
?

**Comment by shakyShane** [comment]
Done

**Comment by shakyShane** [comment]
you can publish now

**Comment by shakyShane** [comment]
Will do the same on svg-sprite-data
