### ISSUE TITLE
Can't color the svgs with css

### ISSUE THREAD

**Issue by bambamboole** [shakyShane/gulp-svg-sprites#88]
Hey,

I can't color my svgs with CSS like this:

```
.icon.google:before {
      background-position: 0em -3.3125em;
      width: 0.9375em;
      height: 0.9375em;
      fill: red;
  }
```

either this:

```
<span class="icon google" style="fill: red;"></span>
```

What am I doing wrong?
Is there a possibility to style the svgs via CSS?

cheers
bambamboole

**Comment by pppglowacki** [comment]
@bambamboole I also cannot style the svg using css. any help would be appreciated.

**Comment by sp90** [comment]
Bump, this is an old question - anyone?

**Comment by Ajeey** [comment]
Bump!

**Comment by Khaleel** [comment]
You cannot fill SVG likes that in CSS. You need to use another approach.

https://una.im/svg-icons/#%F0%9F%92%81

**Comment by soenkekluth** [comment]
@Khaleel is right
